"""
Job: publish
Reads runs/<run_id>/propose.json and review.json, applies the review decisions, builds an Ossie
semantic model, validates it against the vendored spec, and writes it to models/published/<model>.ossie.yaml
(plus .json). Commit the result with git to version it.

Environment:
  HELIOS_RUN_ID        run to publish from (default: latest)
  HELIOS_MODEL_NAME    Ossie model name (default: the harvested database name, e.g. tpcds)
  HELIOS_ACCEPT_PENDING  "1" to treat un-reviewed elements as accepted (default: rejected)
"""
import json
import os
import sys

ROOT = os.environ.get("HELIOS_ROOT") or os.path.join(os.environ.get("CDSW_PROJECT_DIR", "/home/cdsw"), "helios")
sys.path.insert(0, os.path.join(ROOT, "jobs"))
from _common import latest_run_id, read_json, run_path  # noqa: E402

from helios_core import review as rv  # noqa: E402
from helios_core.ossie import build, dump_yaml, validate  # noqa: E402

run_id = os.environ.get("HELIOS_RUN_ID") or latest_run_id()
if not run_id:
    raise SystemExit("no run found")
proposal = read_json(run_path(run_id, "propose.json"))
harvest = read_json(run_path(run_id, "harvest.json"))
review = rv.load(run_path(run_id, "review.json"), run_id)
model_name = os.environ.get("HELIOS_MODEL_NAME") or (harvest.get("databases") or ["helios"])[0]
accept_pending = os.environ.get("HELIOS_ACCEPT_PENDING") == "1"

reviewed = rv.apply(proposal, review, accept_pending=accept_pending)
doc, problems = build(reviewed, model_name, description=f"Semantic model for {model_name}, generated by helios run {run_id}", run_id=run_id)
errors = [f"metric {p}" for p in problems] + validate(doc)
if errors:
    for e in errors:
        print(f"  INVALID: {e}")
    raise SystemExit(f"{len(errors)} validation error(s); nothing written")

out_dir = os.path.join(ROOT, "models", "published")
os.makedirs(out_dir, exist_ok=True)
with open(os.path.join(out_dir, f"{model_name}.ossie.yaml"), "w") as f:
    f.write(dump_yaml(doc))
with open(os.path.join(out_dir, f"{model_name}.ossie.json"), "w") as f:
    json.dump(doc, f, indent=2)
print(f"published {model_name}: datasets={len(doc['datasets'])} relationships={len(doc['relationships'])} "
      f"metrics={len(doc['metrics'])} -> {out_dir}/{model_name}.ossie.yaml")
