-- Generated by `python -m helios_ds.lakehouse`; do not edit by hand.
-- Tests fail if this file is out of date with helios_ds.schemas.

CREATE DATABASE IF NOT EXISTS helios_ds;

CREATE TABLE IF NOT EXISTS helios_ds.datasets (
  dataset_id STRING,
  config_hash STRING,
  config_json STRING,
  template_bundle_hash STRING,
  source_fingerprint_hash STRING,
  source_fingerprint_json STRING,
  generator_version STRING,
  generator_schema_version STRING,
  python_version STRING,
  container_digest STRING,
  manifest_locator STRING,
  manifest_sha256 STRING,
  scenario_count BIGINT,
  planned_artifact_count BIGINT
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.generation_runs (
  run_id STRING,
  dataset_id STRING,
  job_id STRING,
  started_at STRING,
  finished_at STRING,
  outcome STRING,
  error STRING,
  python_version STRING,
  platform STRING,
  container_digest STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.dataset_lifecycle (
  dataset_id STRING,
  event_seq BIGINT,
  state STRING,
  run_id STRING,
  actor STRING,
  occurred_at STRING,
  reason STRING,
  related_dataset_id STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.scenario_plans (
  dataset_id STRING,
  scenario_id STRING,
  scenario_type STRING,
  business_key STRING,
  rank_score STRING,
  scenario_seed STRING,
  source_refs STRING,
  facts STRING,
  artifact_plan STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.template_versions (
  dataset_id STRING,
  template_id STRING,
  template_version STRING,
  template_schema_version STRING,
  artifact_type STRING,
  content_hash STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.generation_jobs (
  job_id STRING,
  created_at STRING,
  config_hash STRING,
  config_json STRING,
  request STRING,
  request_hash STRING,
  idempotency_key STRING,
  dispatcher STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.job_events (
  event_id STRING,
  job_id STRING,
  occurred_at STRING,
  state STRING,
  progress_percent BIGINT,
  actor STRING,
  dataset_id STRING,
  workbench_run_id STRING,
  message STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.review_marks (
  dataset_id STRING,
  mark_id STRING,
  artifact_id STRING,
  status STRING,
  note STRING,
  reviewer STRING,
  created_at STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.artifacts (
  dataset_id STRING,
  artifact_id STRING,
  scenario_id STRING,
  artifact_type STRING,
  mime_type STRING,
  source_locator STRING,
  sha256 STRING,
  size_bytes BIGINT,
  semantic_timestamp STRING,
  template_id STRING,
  template_version STRING,
  acl_policy_id STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.artifact_sources (
  dataset_id STRING,
  artifact_id STRING,
  source_table STRING,
  source_key STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.source_principals (
  dataset_id STRING,
  principal_id STRING,
  principal_type STRING,
  name STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ds.source_acl_bindings (
  dataset_id STRING,
  acl_policy_id STRING,
  artifact_id STRING,
  principal_id STRING,
  permission STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE DATABASE IF NOT EXISTS helios_ground_truth;

CREATE TABLE IF NOT EXISTS helios_ground_truth.entities (
  dataset_id STRING,
  entity_id STRING,
  entity_type STRING,
  source_key STRING,
  canonical_name STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ground_truth.entity_mentions (
  dataset_id STRING,
  mention_id STRING,
  entity_id STRING,
  artifact_id STRING,
  surface_form STRING,
  modality STRING,
  start_offset BIGINT,
  end_offset BIGINT,
  scenario_id STRING,
  entity_type STRING,
  locator STRING,
  difficulty STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ground_truth.relationships (
  dataset_id STRING,
  relationship_id STRING,
  source_entity_id STRING,
  predicate STRING,
  target_entity_id STRING,
  confidence DOUBLE,
  scenario_id STRING,
  artifact_id STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ground_truth.claims (
  dataset_id STRING,
  claim_id STRING,
  scenario_id STRING,
  claim_type STRING,
  subject STRING,
  obj STRING,
  truth_status STRING,
  statement STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ground_truth.evidence (
  dataset_id STRING,
  evidence_id STRING,
  claim_id STRING,
  artifact_id STRING,
  segment_id STRING,
  start_offset BIGINT,
  end_offset BIGINT,
  locator_type STRING,
  scenario_id STRING,
  locator STRING,
  excerpt STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ground_truth.expected_queries (
  dataset_id STRING,
  query_id STRING,
  question STRING,
  principal_id STRING,
  required_structured STRING,
  required_entities STRING,
  required_artifacts STRING,
  required_claims STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_ground_truth.expected_results (
  dataset_id STRING,
  result_id STRING,
  query_id STRING,
  result_type STRING,
  result_data STRING
)
STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');
