"""helios_index administration.

python -m helios_core.index ddl          print the Impala DDL (for Hue / impala-shell)
python -m helios_core.index init-tables  create the tables through Impala (Helios settings)
"""

from __future__ import annotations

import sys

from .store import impala_index_store
from .tables import ddl_statements


def impala_ddl() -> str:
    lines = [
        "-- Generated by `python -m helios_core.index ddl`; do not edit by hand.",
        "-- Tests fail if this file is out of date with helios_core.index.records.",
    ]
    for statement in ddl_statements():
        lines += ["", f"{statement};"]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    command = argv[0] if argv else "ddl"
    if command == "ddl":
        sys.stdout.write(impala_ddl())
        return 0
    if command == "init-tables":
        store = impala_index_store()
        if store is None:
            print("Impala is not configured (IMPALA_HOST, WORKLOAD_USER, WORKLOAD_PASSWORD).")
            return 2
        store.ensure_tables()
        print("helios_index tables are in place.")
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
