-- Generated by `python -m helios_core.index ddl`; do not edit by hand.
-- Tests fail if this file is out of date with helios_core.index.records.

CREATE DATABASE IF NOT EXISTS helios_index;

CREATE TABLE IF NOT EXISTS helios_index.ontology_versions (
  version STRING,
  content_hash STRING,
  schema_path STRING,
  published_at STRING,
  published_by STRING,
  node_count BIGINT,
  edge_count BIGINT,
  graph_json STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.ontology_activations (
  version STRING,
  content_hash STRING,
  activated_at STRING,
  activated_by STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.crawl_runs (
  crawl_run_id STRING,
  connector STRING,
  source STRING,
  ontology_version STRING,
  crawler_version STRING,
  status STRING,
  started_at STRING,
  recorded_at STRING,
  actor STRING,
  finished_at STRING,
  settings STRING,
  counts STRING,
  error STRING,
  settings_version BIGINT,
  settings_hash STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.assets (
  crawl_run_id STRING,
  asset_id STRING,
  asset_version_id STRING,
  connector STRING,
  source STRING,
  ontology_class STRING,
  mime_type STRING,
  source_locator STRING,
  size_bytes BIGINT,
  semantic_timestamp STRING,
  ontology_version STRING,
  status STRING,
  status_detail STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.segments (
  crawl_run_id STRING,
  segment_id STRING,
  asset_id STRING,
  segment_type STRING,
  ordinal BIGINT,
  locator STRING,
  text STRING,
  ontology_version STRING,
  structure STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.mentions (
  crawl_run_id STRING,
  mention_id STRING,
  asset_id STRING,
  segment_id STRING,
  surface_form STRING,
  locator STRING,
  proposed_class STRING,
  extractor STRING,
  extractor_detail STRING,
  start_offset BIGINT,
  end_offset BIGINT,
  ontology_version STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.entities (
  crawl_run_id STRING,
  entity_id STRING,
  ontology_class STRING,
  canonical_name STRING,
  external_ids STRING,
  ontology_version STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.entity_links (
  crawl_run_id STRING,
  link_id STRING,
  mention_id STRING,
  entity_id STRING,
  link_type STRING,
  resolved_by STRING,
  score DOUBLE,
  evidence_segment_ids STRING,
  ontology_version STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.relationships (
  crawl_run_id STRING,
  relationship_id STRING,
  relationship_type STRING,
  source_kind STRING,
  source_id STRING,
  target_kind STRING,
  target_id STRING,
  resolved_by STRING,
  confidence DOUBLE,
  evidence_segment_ids STRING,
  ontology_version STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.claims (
  crawl_run_id STRING,
  claim_id STRING,
  predicate STRING,
  subject_entity_id STRING,
  object_entity_id STRING,
  object_value STRING,
  confidence DOUBLE,
  extractor STRING,
  ontology_version STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.claim_evidence (
  crawl_run_id STRING,
  claim_id STRING,
  evidence_id STRING,
  asset_id STRING,
  segment_id STRING,
  locator STRING,
  excerpt STRING,
  ontology_version STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.crawler_settings (
  version BIGINT,
  content_hash STRING,
  settings_json STRING,
  created_at STRING,
  created_by STRING,
  note STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.crawler_settings_activations (
  version BIGINT,
  content_hash STRING,
  activated_at STRING,
  activated_by STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.evaluations (
  evaluation_id STRING,
  crawl_run_id STRING,
  dataset_id STRING,
  evaluated_at STRING,
  evaluator STRING,
  evaluator_mode STRING,
  harness_version STRING,
  ontology_version STRING,
  strategy STRING,
  metrics STRING,
  summary STRING,
  status STRING,
  error STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.coverage (
  crawl_run_id STRING,
  signal STRING,
  value STRING,
  count BIGINT,
  example STRING,
  ontology_version STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.mappings (
  version BIGINT,
  model STRING,
  ontology_version STRING,
  content_hash STRING,
  mapping_json STRING,
  created_at STRING,
  created_by STRING,
  note STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');

CREATE TABLE IF NOT EXISTS helios_index.mapping_activations (
  version BIGINT,
  model STRING,
  content_hash STRING,
  activated_at STRING,
  activated_by STRING
) STORED AS ICEBERG TBLPROPERTIES ('format-version'='2');
