"""Prepare and publish reviewed discovery proposals.

This module is transport-neutral so the legacy Console and the authorized API
use the same review application, Ossie validation, and artifact writes.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import review as review_store
from .artifacts import ArtifactStore
from .ossie import build, dump_yaml, preflight, validate


@dataclass(frozen=True)
class PreparedPublication:
    document: dict[str, Any]
    reviewed_proposal: dict[str, Any]
    errors: tuple[str, ...]
    preflight_issues: dict[str, str]


@dataclass(frozen=True)
class PublicationResult:
    manifest: dict[str, Any]
    yaml_path: Path
    document: dict[str, Any]


class PublicationValidationError(ValueError):
    def __init__(self, errors: tuple[str, ...]):
        self.errors = errors
        super().__init__("; ".join(errors))


def model_name_for_proposal(
    proposal: dict[str, Any],
    harvest: dict[str, Any],
) -> str:
    databases = harvest.get("databases") or []
    if databases:
        return str(databases[0])
    datasets = proposal.get("datasets") or []
    if datasets:
        return str(datasets[0]["table"]).split(".")[0]
    return "helios"


def prepare_reviewed_publication(
    *,
    model_id: str,
    model_name: str,
    run_id: str,
    proposal: dict[str, Any],
    review: dict[str, Any],
) -> PreparedPublication:
    reviewed = review_store.apply(proposal, review)
    document, metric_problems = build(
        reviewed,
        model_name,
        description=(
            f"Semantic model for {model_name}, generated by helios run {run_id}"
        ),
        run_id=run_id,
        model_id=model_id,
    )
    errors = [
        f"metric {problem} — reject it or edit the expression"
        for problem in metric_problems
    ]
    errors.extend(validate(document))
    return PreparedPublication(
        document=document,
        reviewed_proposal=reviewed,
        errors=tuple(errors),
        preflight_issues=preflight(proposal),
    )


def publish_reviewed_proposal(
    artifacts: ArtifactStore,
    *,
    model_id: str,
    model_name: str,
    run_id: str,
    proposal: dict[str, Any],
    review: dict[str, Any],
) -> PublicationResult:
    prepared = prepare_reviewed_publication(
        model_id=model_id,
        model_name=model_name,
        run_id=run_id,
        proposal=proposal,
        review=review,
    )
    if prepared.errors:
        raise PublicationValidationError(prepared.errors)

    document = prepared.document
    manifest = {
        "model_id": model_id,
        "run_id": run_id,
        "published_at": datetime.now(timezone.utc).isoformat(),
        "datasets": len(document["datasets"]),
        "relationships": len(document["relationships"]),
        "metrics": len(document["metrics"]),
        "review": prepared.reviewed_proposal.get("review"),
    }
    yaml_path, _, _ = artifacts.write_published_ossie(
        model_id,
        document,
        dump_yaml(document),
        manifest,
    )
    return PublicationResult(manifest, yaml_path, document)
